package stat

import (
	"github.com/stretchr/testify/assert"
	"github.com/teamyapp/experimental/yijia-cc/prototypes/codejelly/entity"
	"github.com/teamyapp/experimental/yijia-cc/prototypes/codejelly/git"
	"github.com/teamyapp/experimental/yijia-cc/prototypes/codejelly/service"
	"testing"
)

func TestComputeFileDiffStats(t *testing.T) {
	testCases := []struct {
		name string
		block string
		fileContent string
		expected entity.FileDiffStatistics
		expectedHasErr bool
	} {
		{
			name: "multiple hunks",
			block:
`diff --git a/calendar/dep/wire_gen.go b/calendar/dep/wire_gen.go
index 393ac2d..5ba68ad 100644
--- a/calendar/dep/wire_gen.go
+++ b/calendar/dep/wire_gen.go
@@ -7,14 +7,13 @@ package dep
 
 import (
 	"database/sql"
-	"net/http"
-
 	"github.com/yijia-cc/grouplive/calendar/auth"
 	"github.com/yijia-cc/grouplive/calendar/config"
 	"github.com/yijia-cc/grouplive/calendar/db/dao"
 	"github.com/yijia-cc/grouplive/calendar/gql"
 	"github.com/yijia-cc/grouplive/calendar/obs"
 	"github.com/yijia-cc/grouplive/calendar/tx"
+	"net/http"
 )
 
 // Injectors from wire.go:
@@ -27,7 +26,10 @@ func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.
 	safeTransactionFactory := tx.NewSafeTransactionFactory(db)
 	amenitySQL := dao.NewAmenitySQL(db)
 	amenityTypeSQL := dao.NewAmenityTypeSQL(db)
-	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL)
+	timeSlotSQL := dao.NewTimeSlotSQL(db)
+	reservationSQL := dao.NewReservationSQL(db)
+	weekSQL := dao.NewWeekSQL(db)
+	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL, timeSlotSQL, reservationSQL, weekSQL)
 	return serveMux, nil
 }
 
`,
			fileContent:
`// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dep

import (
	"database/sql"
	"net/http"

	"github.com/yijia-cc/grouplive/calendar/auth"
	"github.com/yijia-cc/grouplive/calendar/config"
	"github.com/yijia-cc/grouplive/calendar/db/dao"
	"github.com/yijia-cc/grouplive/calendar/gql"
	"github.com/yijia-cc/grouplive/calendar/obs"
	"github.com/yijia-cc/grouplive/calendar/tx"
)

// Injectors from wire.go:

func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.ServeMux, error) {
	groupLiveAuthClient, err := newGroupLiveAuthClient(cfg)
	if err != nil {
		return nil, err
	}
	safeTransactionFactory := tx.NewSafeTransactionFactory(db)
	amenitySQL := dao.NewAmenitySQL(db)
	amenityTypeSQL := dao.NewAmenityTypeSQL(db)
	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL)
	return serveMux, nil
}

// wire.go:

func newGroupLiveAuthClient(cfg config.Config) (auth.GroupLiveAuthClient, error) {
	return auth.NewGroupLiveAuthClient(cfg.AuthGRPCEndpoint)
}
`,
			expected: entity.FileDiffStatistics{
				NumOfDeletedLines: 3,
				NumOfAddedLines: 5,
				NumOfLinesChanged: 8,
				FromFileTotalNumOfLines: 39,
				ToFileTotalNumOfLines: 41,
			},
			expectedHasErr: false,
		},
		{
			name: "single block",
			block:
`diff --git a/calendar/gql/resolver/reservation_status.go b/calendar/gql/resolver/reservation_status.go
index 7c3e185..24e19fc 100644
--- a/calendar/gql/resolver/reservation_status.go
+++ b/calendar/gql/resolver/reservation_status.go
@@ -1,9 +1,17 @@
 package resolver
 
+import "github.com/yijia-cc/grouplive/calendar/entity"
+
 type ReservationStatus string
 
 const (
	upcoming ReservationStatus = "UPCOMING"
 	ongoing                    = "ONGOING"
 	past                       = "PAST"
 )
+
+var reservationStatusMap = map[entity.ReservationStatus]ReservationStatus {
+	entity.Upcoming: upcoming,
+	entity.Ongoing: ongoing,
+	entity.Past: past,
+}`,
			fileContent:
`package resolver

type ReservationStatus string

const (
	upcoming ReservationStatus = "UPCOMING"
	ongoing                    = "ONGOING"
	past                       = "PAST"
)
`,
			expected: entity.FileDiffStatistics{
				NumOfDeletedLines: 0,
				NumOfAddedLines: 8,
				NumOfLinesChanged: 8,
				FromFileTotalNumOfLines: 10,
				ToFileTotalNumOfLines: 18,
			},
			expectedHasErr: false,
		},
		{
			name: "test no new line",
			block:
`diff --git a/web/.env.development b/web/.env.development
new file mode 100644
index 0000000..edc67e8
--- /dev/null
+++ b/web/.env.development
@@ -0,0 +1 @@
+REACT_APP_AUTH_API_BASE_URL=http://auth.api.staging.allgame.fun
\ No newline at end of file`,
			expected: entity.FileDiffStatistics{
				NumOfDeletedLines: 0,
				NumOfAddedLines: 1,
				NumOfLinesChanged: 1,
				FromFileTotalNumOfLines: 0,
				ToFileTotalNumOfLines: 1,
			},
			expectedHasErr: false,
		},
	}

	for _, testCase := range testCases {
		testCase := testCase
		t.Run(testCase.name, func(t *testing.T){
			t.Parallel()
			fileDiff, err := git.NewFileDiffFromBlock(testCase.block)
			assert.Nil(t, err)

			chunks := service.GetChunks(fileDiff.Hunks, testCase.fileContent)

			actual, err := ComputeFileDiffStats(entity.FullFileDiff{
				FileDiffHeader: fileDiff.FileDiffHeader,
				Chunks: chunks,
			})

			if testCase.expectedHasErr {
				assert.NotNil(t, err)
			} else {
				assert.Nil(t, err)
			}

			assert.Equal(t, testCase.expected, actual)
		})
	}
}
