package service

import (
	"github.com/stretchr/testify/assert"
	"github.com/teamyapp/experimental/yijia-cc/prototypes/codejelly/entity"
	"github.com/teamyapp/experimental/yijia-cc/prototypes/codejelly/git"
	"testing"
)

func TestGetFile(t *testing.T) {
	testCases := []struct {
		name string
		block string
		fullFile string
		expected entity.FullFileDiff
		expectedHasErr bool
	} {
		{
			name: "comprehensive example",
			block: `
diff --git a/calendar/dep/wire_gen.go b/calendar/dep/wire_gen.go
index 393ac2d..5ba68ad 100644
--- a/calendar/dep/wire_gen.go
+++ b/calendar/dep/wire_gen.go
@@ -7,14 +7,13 @@ package dep
 
 import (
 	"database/sql"
-	"net/http"
-
 	"github.com/yijia-cc/grouplive/calendar/auth"
 	"github.com/yijia-cc/grouplive/calendar/config"
 	"github.com/yijia-cc/grouplive/calendar/db/dao"
 	"github.com/yijia-cc/grouplive/calendar/gql"
 	"github.com/yijia-cc/grouplive/calendar/obs"
 	"github.com/yijia-cc/grouplive/calendar/tx"
+	"net/http"
 )
 
 // Injectors from wire.go:
@@ -27,7 +26,10 @@ func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.
 	safeTransactionFactory := tx.NewSafeTransactionFactory(db)
 	amenitySQL := dao.NewAmenitySQL(db)
 	amenityTypeSQL := dao.NewAmenityTypeSQL(db)
-	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL)
+	timeSlotSQL := dao.NewTimeSlotSQL(db)
+	reservationSQL := dao.NewReservationSQL(db)
+	weekSQL := dao.NewWeekSQL(db)
+	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL, timeSlotSQL, reservationSQL, weekSQL)
 	return serveMux, nil
 }
 
`,
			fullFile: `
// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dep

import (
	"database/sql"
	"net/http"

	"github.com/yijia-cc/grouplive/calendar/auth"
	"github.com/yijia-cc/grouplive/calendar/config"
	"github.com/yijia-cc/grouplive/calendar/db/dao"
	"github.com/yijia-cc/grouplive/calendar/gql"
	"github.com/yijia-cc/grouplive/calendar/obs"
	"github.com/yijia-cc/grouplive/calendar/tx"
)

// Injectors from wire.go:

func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.ServeMux, error) {
	groupLiveAuthClient, err := newGroupLiveAuthClient(cfg)
	if err != nil {
		return nil, err
	}
	safeTransactionFactory := tx.NewSafeTransactionFactory(db)
	amenitySQL := dao.NewAmenitySQL(db)
	amenityTypeSQL := dao.NewAmenityTypeSQL(db)
	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL)
	return serveMux, nil
}

// wire.go:

func newGroupLiveAuthClient(cfg config.Config) (auth.GroupLiveAuthClient, error) {
	return auth.NewGroupLiveAuthClient(cfg.AuthGRPCEndpoint)
}`,
			expected: entity.FullFileDiff{
				FileDiffHeader: entity.FileDiffHeader{
					Status: entity.ChangeModified,
					FromFilePath: "calendar/dep/wire_gen.go",
					ToFilePath: "calendar/dep/wire_gen.go",
					Similarity: 0,
				},
				Chunks: []entity.Chunk{
					{
						NumberedLines: []entity.NumberedLine{
							{
								Status: entity.LineUnchanged,
								Content: "// Code generated by Wire. DO NOT EDIT.",
								FromFileLineNumber: 1,
								ToFileLineNumber: 1,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 2,
								ToFileLineNumber: 2,
							},
							{
								Status: entity.LineUnchanged,
								Content: "//go:generate go run github.com/google/wire/cmd/wire",
								FromFileLineNumber: 3,
								ToFileLineNumber: 3,
							},
							{
								Status: entity.LineUnchanged,
								Content: "//+build !wireinject",
								FromFileLineNumber: 4,
								ToFileLineNumber: 4,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 5,
								ToFileLineNumber: 5,
							},
							{
								Status: entity.LineUnchanged,
								Content: "package dep",
								FromFileLineNumber: 6,
								ToFileLineNumber: 6,
							},
						},
						IsHunk: false,
					},
					{
						NumberedLines: []entity.NumberedLine {
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 7,
								ToFileLineNumber: 7,

							},
							{
								Status: entity.LineUnchanged,
								Content: "import (",
								FromFileLineNumber: 8,
								ToFileLineNumber: 8,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"database/sql\"",
								FromFileLineNumber: 9,
								ToFileLineNumber: 9,
							},
							{
								Status: entity.LineDeleted,
								Content: "\t\"net/http\"",
								FromFileLineNumber: 10,
								ToFileLineNumber: entity.NoLineNumber,
							},
							{
								Status: entity.LineDeleted,
								Content: "",
								FromFileLineNumber: 11,
								ToFileLineNumber: entity.NoLineNumber,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/auth\"",
								FromFileLineNumber: 12,
								ToFileLineNumber: 10,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/config\"",
								FromFileLineNumber: 13,
								ToFileLineNumber: 11,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/db/dao\"",
								FromFileLineNumber: 14,
								ToFileLineNumber: 12,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/gql\"",
								FromFileLineNumber: 15,
								ToFileLineNumber: 13,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/obs\"",
								FromFileLineNumber: 16,
								ToFileLineNumber: 14,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\"github.com/yijia-cc/grouplive/calendar/tx\"",
								FromFileLineNumber: 17,
								ToFileLineNumber: 15,
							},
							{
								Status: entity.LineAdded,
								Content: "\t\"net/http\"",
								FromFileLineNumber: entity.NoLineNumber,
								ToFileLineNumber: 16,
							},
							{
								Status: entity.LineUnchanged,
								Content: ")",
								FromFileLineNumber: 18,
								ToFileLineNumber: 17,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 19,
								ToFileLineNumber: 18,
							},
							{
								Status: entity.LineUnchanged,
								Content: "// Injectors from wire.go:",
								FromFileLineNumber: 20,
								ToFileLineNumber: 19,
							},
						},
						IsHunk: true,
					},
					{
						NumberedLines: []entity.NumberedLine{
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 21,
								ToFileLineNumber: 20,
							},
							{
								Status: entity.LineUnchanged,
								Content: "func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.ServeMux, error) {",
								FromFileLineNumber: 22,
								ToFileLineNumber: 21,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\tgroupLiveAuthClient, err := newGroupLiveAuthClient(cfg)",
								FromFileLineNumber: 23,
								ToFileLineNumber: 22,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\tif err != nil {",
								FromFileLineNumber: 24,
								ToFileLineNumber: 23,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t\treturn nil, err",
								FromFileLineNumber: 25,
								ToFileLineNumber: 24,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\t}",
								FromFileLineNumber: 26,
								ToFileLineNumber: 25,
							},
						},
						IsHunk: false,
					},
					{
						NumberedLines: []entity.NumberedLine{
							{
								Status: entity.LineUnchanged,
								Content: "\tsafeTransactionFactory := tx.NewSafeTransactionFactory(db)",
								FromFileLineNumber: 27,
								ToFileLineNumber: 26,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\tamenitySQL := dao.NewAmenitySQL(db)",
								FromFileLineNumber: 28,
								ToFileLineNumber: 27,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\tamenityTypeSQL := dao.NewAmenityTypeSQL(db)",
								FromFileLineNumber: 29,
								ToFileLineNumber: 28,
							},
							{
								Status: entity.LineDeleted,
								Content: "\tserveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL)",
								FromFileLineNumber: 30,
								ToFileLineNumber: entity.NoLineNumber,
							},
							{
								Status: entity.LineAdded,
								Content: "\ttimeSlotSQL := dao.NewTimeSlotSQL(db)",
								FromFileLineNumber: entity.NoLineNumber,
								ToFileLineNumber: 29,
							},
							{
								Status: entity.LineAdded,
								Content: "\treservationSQL := dao.NewReservationSQL(db)",
								FromFileLineNumber: entity.NoLineNumber,
								ToFileLineNumber: 30,
							},
							{
								Status: entity.LineAdded,
								Content: "\tweekSQL := dao.NewWeekSQL(db)",
								FromFileLineNumber: entity.NoLineNumber,
								ToFileLineNumber: 31,
							},
							{
								Status: entity.LineAdded,
								Content: "\tserveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL, timeSlotSQL, reservationSQL, weekSQL)",
								FromFileLineNumber: entity.NoLineNumber,
								ToFileLineNumber: 32,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\treturn serveMux, nil",
								FromFileLineNumber: 31,
								ToFileLineNumber: 33,
							},
							{
								Status: entity.LineUnchanged,
								Content: "}",
								FromFileLineNumber: 32,
								ToFileLineNumber: 34,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 33,
								ToFileLineNumber: 35,
							},
						},
						IsHunk: true,
					},
					{
						NumberedLines: []entity.NumberedLine{
							{
								Status: entity.LineUnchanged,
								Content: "// wire.go:",
								FromFileLineNumber: 34,
								ToFileLineNumber: 36,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 35,
								ToFileLineNumber: 37,
							},
							{
								Status: entity.LineUnchanged,
								Content: "func newGroupLiveAuthClient(cfg config.Config) (auth.GroupLiveAuthClient, error) {",
								FromFileLineNumber: 36,
								ToFileLineNumber: 38,
							},
							{
								Status: entity.LineUnchanged,
								Content: "\treturn auth.NewGroupLiveAuthClient(cfg.AuthGRPCEndpoint)",
								FromFileLineNumber: 37,
								ToFileLineNumber: 39,
							},
							{
								Status: entity.LineUnchanged,
								Content: "}",
								FromFileLineNumber: 38,
								ToFileLineNumber: 40,
							},
							{
								Status: entity.LineUnchanged,
								Content: "",
								FromFileLineNumber: 39,
								ToFileLineNumber: 41,
							},
						},
						IsHunk: false,
					},
				},
			},
		},
	}
	for _, testCase := range testCases {
		testCase := testCase
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			fileDiff, err := git.NewFileDiffFromBlock(testCase.block)
			if err != nil {
				assert.Fail(t, "fail")
			}
			g := git.NewRepo("/Users/yijiacc/Documents/projects/laiprojects/grouplive")
			diff := NewDiff(g)
			actual, err := diff.GetFile(fileDiff, "yijia-cc/feature-find-amenity-type")
			if testCase.expectedHasErr {
				assert.NotNil(t, err)
				return
			} else {
				assert.Nil(t, err)
			}
			assert.Equal(t, testCase.expected, actual)
		})
	}
}
