apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: identity
  labels:
    app: identity
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: harbor.internal.teamyapp.com/internal/identity-testing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: harbor-cred
---
apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: identity
spec:
  selector:
    app: identity
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: testing
  name: identity
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`identity.testing.teamyapp.com`)
      services:
        - kind: Service
          name: identity
          namespace: testing
          port: 80
          passHostHeader: true
  tls:
    secretName: teamy-cert

